blank_issues_enabled: true
contact_links:
  - name: General Feedback & Questions
    url: https://github.com/contour-terminal/contour/discussions
    about: For general questions, ideas, and feedback â€” please use GitHub Discussions.
