name: Checks

on:
  push:
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/*.yml'
    - 'LICENSE.txt'
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_PR_TODOs:
    name: "Check PR-TODOs"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: "Checking for open PR-related TODO items"
      run: |
        set -ex
        ./scripts/check-pr-todos.sh

  check_clang_format:
    name: "Check C++ style"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.4.0
      with:
        clang-format-version: '14'
        check-path: 'src'
        exclude-regex: 'crispy/sse2neon.h'



